version: 2.0


workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
    build:
      docker:
        - image: circleci/openjdk:stretch
          environment:
            JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/javavideos
            JDBC_DATABASE_USERNAME: root
            JDBC_DATABASE_PASSWORD: root

        - image: circleci/postgres:13.0-alpine
        environment:
          POSTGRES_DB: javavideos

      working-directory: ~/springboot-ci-cd-cd-example

      environment:
        MAVEN_OPTS: -Xmx3200m

      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
              - v1-dependencies- # fallback in case previous cache key is not found

        - run: mvn dependency:go-offline

        - save_cache:
            paths:
              - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}

        - run: mvn test