version: 2.0

jobs:

  build:
    docker:
      - image: circleci/openjdk:stretch
        environment:
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/javavideos
          JDBC_DATABASE_USERNAME: postgres
          JDBC_DATABASE_PASSWORD: password

      - image: circleci/postgres:12.4-postgis-ram
        environment:
          POSTGRES_DB: javavideos

    working-directory: ~/springboot-ci-cd-cd-example

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout

    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
          - v1-dependencies- # fallback in case previous cache key is not found

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - run: mvn test